apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: tasky
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-admin
      containers:
      - name: tasky
        image: 034362065257.dkr.ecr.us-east-1.amazonaws.com/tasky:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password123@10.0.48.17:27017/admin?retryWrites=true&connectTimeoutMS=30000&socketTimeoutMS=45000"
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: wizexercise-volume
          mountPath: /app/wizexercise.txt
          subPath: wizexercise.txt
      volumes:
      - name: wizexercise-volume
        configMap:
          name: tasky-config
